/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.parser.antlr;

import com.google.inject.Inject;
import it.csec.xtext.parser.antlr.internal.InternalVsdlParser;
import it.csec.xtext.services.VsdlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VsdlParser extends AbstractAntlrParser {

	@Inject
	private VsdlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVsdlParser createParser(XtextTokenStream stream) {
		return new InternalVsdlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VsdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VsdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
