/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.ui;

import com.google.inject.Injector;
import it.csec.xtext.vsdl.ui.internal.VsdlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VsdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VsdlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VsdlActivator activator = VsdlActivator.getInstance();
		return activator != null ? activator.getInjector(VsdlActivator.IT_CSEC_XTEXT_VSDL) : null;
	}

}
