/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VsdlStandaloneSetup extends VsdlStandaloneSetupGenerated {

	public static void doSetup() {
		new VsdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
