/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VsdlUiModule extends AbstractVsdlUiModule {

	public VsdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
