/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.csec.xtext.VsdlRuntimeModule;
import it.csec.xtext.VsdlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VsdlIdeSetup extends VsdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VsdlRuntimeModule(), new VsdlIdeModule()));
	}
	
}
