/*
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVsdlScopeProvider extends DelegatingScopeProvider {
}
