/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.ConfigOptions#getConfigPairs <em>Config Pairs</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getConfigOptions()
 * @model
 * @generated
 */
public interface ConfigOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Config Pairs</b></em>' containment reference list.
   * The list contents are of type {@link it.csec.xtext.vsdl.ConfigPair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Config Pairs</em>' containment reference list.
   * @see it.csec.xtext.vsdl.VsdlPackage#getConfigOptions_ConfigPairs()
   * @model containment="true"
   * @generated
   */
  EList<ConfigPair> getConfigPairs();

} // ConfigOptions
