/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flavour</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.Flavour#getProfile <em>Profile</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getFlavour()
 * @model
 * @generated
 */
public interface Flavour extends NodeConstraint
{
  /**
   * Returns the value of the '<em><b>Profile</b></em>' attribute.
   * The literals are from the enumeration {@link it.csec.xtext.vsdl.HardwareProfile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Profile</em>' attribute.
   * @see it.csec.xtext.vsdl.HardwareProfile
   * @see #setProfile(HardwareProfile)
   * @see it.csec.xtext.vsdl.VsdlPackage#getFlavour_Profile()
   * @model
   * @generated
   */
  HardwareProfile getProfile();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Flavour#getProfile <em>Profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Profile</em>' attribute.
   * @see it.csec.xtext.vsdl.HardwareProfile
   * @see #getProfile()
   * @generated
   */
  void setProfile(HardwareProfile value);

} // Flavour
