/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gateway</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.Gateway#getGatewayIP <em>Gateway IP</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.Gateway#isInternet <em>Internet</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getGateway()
 * @model
 * @generated
 */
public interface Gateway extends NodeConstraint, NetworkConstraint
{
  /**
   * Returns the value of the '<em><b>Gateway IP</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gateway IP</em>' containment reference.
   * @see #setGatewayIP(IPAddress)
   * @see it.csec.xtext.vsdl.VsdlPackage#getGateway_GatewayIP()
   * @model containment="true"
   * @generated
   */
  IPAddress getGatewayIP();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Gateway#getGatewayIP <em>Gateway IP</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gateway IP</em>' containment reference.
   * @see #getGatewayIP()
   * @generated
   */
  void setGatewayIP(IPAddress value);

  /**
   * Returns the value of the '<em><b>Internet</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internet</em>' attribute.
   * @see #setInternet(boolean)
   * @see it.csec.xtext.vsdl.VsdlPackage#getGateway_Internet()
   * @model
   * @generated
   */
  boolean isInternet();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Gateway#isInternet <em>Internet</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Internet</em>' attribute.
   * @see #isInternet()
   * @generated
   */
  void setInternet(boolean value);

} // Gateway
