/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.IP#getOp <em>Op</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getIpAddress <em>Ip Address</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getIpRange <em>Ip Range</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#isSameas <em>Sameas</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getId <em>Id</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getIp <em>Ip</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getIP()
 * @model
 * @generated
 */
public interface IP extends NodeConstraint
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Ip Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip Address</em>' containment reference.
   * @see #setIpAddress(IPAddress)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_IpAddress()
   * @model containment="true"
   * @generated
   */
  IPAddress getIpAddress();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getIpAddress <em>Ip Address</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip Address</em>' containment reference.
   * @see #getIpAddress()
   * @generated
   */
  void setIpAddress(IPAddress value);

  /**
   * Returns the value of the '<em><b>Ip Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip Range</em>' containment reference.
   * @see #setIpRange(IPRangeA)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_IpRange()
   * @model containment="true"
   * @generated
   */
  IPRangeA getIpRange();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getIpRange <em>Ip Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip Range</em>' containment reference.
   * @see #getIpRange()
   * @generated
   */
  void setIpRange(IPRangeA value);

  /**
   * Returns the value of the '<em><b>Sameas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sameas</em>' attribute.
   * @see #setSameas(boolean)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Sameas()
   * @model
   * @generated
   */
  boolean isSameas();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#isSameas <em>Sameas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sameas</em>' attribute.
   * @see #isSameas()
   * @generated
   */
  void setSameas(boolean value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(Node)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Id()
   * @model
   * @generated
   */
  Node getId();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(Node value);

  /**
   * Returns the value of the '<em><b>Ip</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' containment reference.
   * @see #setIp(IPAddress)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Ip()
   * @model containment="true"
   * @generated
   */
  IPAddress getIp();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getIp <em>Ip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' containment reference.
   * @see #getIp()
   * @generated
   */
  void setIp(IPAddress value);

} // IP
