/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.IP#getOp <em>Op</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getIpAddress <em>Ip Address</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getIpRange <em>Ip Range</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IP#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getIP()
 * @model
 * @generated
 */
public interface IP extends NodeConstraint
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Ip Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip Address</em>' containment reference.
   * @see #setIpAddress(IPAddress)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_IpAddress()
   * @model containment="true"
   * @generated
   */
  IPAddress getIpAddress();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getIpAddress <em>Ip Address</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip Address</em>' containment reference.
   * @see #getIpAddress()
   * @generated
   */
  void setIpAddress(IPAddress value);

  /**
   * Returns the value of the '<em><b>Ip Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip Range</em>' containment reference.
   * @see #setIpRange(IPRangeA)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_IpRange()
   * @model containment="true"
   * @generated
   */
  IPRangeA getIpRange();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getIpRange <em>Ip Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip Range</em>' containment reference.
   * @see #getIpRange()
   * @generated
   */
  void setIpRange(IPRangeA value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' reference.
   * @see #setNode(Node)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIP_Node()
   * @model
   * @generated
   */
  Node getNode();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IP#getNode <em>Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' reference.
   * @see #getNode()
   * @generated
   */
  void setNode(Node value);

} // IP
