/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IP Address</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.IPAddress#getOctet1 <em>Octet1</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IPAddress#getOctet2 <em>Octet2</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IPAddress#getOctet3 <em>Octet3</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.IPAddress#getOctet4 <em>Octet4</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getIPAddress()
 * @model
 * @generated
 */
public interface IPAddress extends EObject
{
  /**
   * Returns the value of the '<em><b>Octet1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Octet1</em>' attribute.
   * @see #setOctet1(int)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIPAddress_Octet1()
   * @model
   * @generated
   */
  int getOctet1();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IPAddress#getOctet1 <em>Octet1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Octet1</em>' attribute.
   * @see #getOctet1()
   * @generated
   */
  void setOctet1(int value);

  /**
   * Returns the value of the '<em><b>Octet2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Octet2</em>' attribute.
   * @see #setOctet2(int)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIPAddress_Octet2()
   * @model
   * @generated
   */
  int getOctet2();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IPAddress#getOctet2 <em>Octet2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Octet2</em>' attribute.
   * @see #getOctet2()
   * @generated
   */
  void setOctet2(int value);

  /**
   * Returns the value of the '<em><b>Octet3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Octet3</em>' attribute.
   * @see #setOctet3(int)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIPAddress_Octet3()
   * @model
   * @generated
   */
  int getOctet3();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IPAddress#getOctet3 <em>Octet3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Octet3</em>' attribute.
   * @see #getOctet3()
   * @generated
   */
  void setOctet3(int value);

  /**
   * Returns the value of the '<em><b>Octet4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Octet4</em>' attribute.
   * @see #setOctet4(int)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIPAddress_Octet4()
   * @model
   * @generated
   */
  int getOctet4();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IPAddress#getOctet4 <em>Octet4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Octet4</em>' attribute.
   * @see #getOctet4()
   * @generated
   */
  void setOctet4(int value);

} // IPAddress
