/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IP Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.IPRange#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getIPRange()
 * @model
 * @generated
 */
public interface IPRange extends NetworkConstraint
{
  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(IPRangeA)
   * @see it.csec.xtext.vsdl.VsdlPackage#getIPRange_Range()
   * @model containment="true"
   * @generated
   */
  IPRangeA getRange();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.IPRange#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(IPRangeA value);

} // IPRange
