/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.Model#getName <em>Name</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.Model#getTimeToUse <em>Time To Use</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.Model#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Time To Use</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time To Use</em>' containment reference.
   * @see #setTimeToUse(TimeInterval)
   * @see it.csec.xtext.vsdl.VsdlPackage#getModel_TimeToUse()
   * @model containment="true"
   * @generated
   */
  TimeInterval getTimeToUse();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Model#getTimeToUse <em>Time To Use</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time To Use</em>' containment reference.
   * @see #getTimeToUse()
   * @generated
   */
  void setTimeToUse(TimeInterval value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link it.csec.xtext.vsdl.ScenElem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see it.csec.xtext.vsdl.VsdlPackage#getModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<ScenElem> getElements();

} // Model
