/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.OS#getVersion <em>Version</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getOS()
 * @model
 * @generated
 */
public interface OS extends NodeConstraint
{
  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getOS_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.OS#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

} // OS
