/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getPlusMinus()
 * @model
 * @generated
 */
public interface PlusMinus extends TimeExpr
{
} // PlusMinus
