/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Software Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.SoftwareDependency#getDependencyID <em>Dependency ID</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getSoftwareDependency()
 * @model
 * @generated
 */
public interface SoftwareDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Dependency ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependency ID</em>' attribute.
   * @see #setDependencyID(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getSoftwareDependency_DependencyID()
   * @model
   * @generated
   */
  String getDependencyID();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.SoftwareDependency#getDependencyID <em>Dependency ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependency ID</em>' attribute.
   * @see #getDependencyID()
   * @generated
   */
  void setDependencyID(String value);

} // SoftwareDependency
