/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.Switch#getVariable <em>Variable</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.Switch#getTexp <em>Texp</em>}</li>
 * </ul>
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getSwitch()
 * @model
 * @generated
 */
public interface Switch extends UpdateTriggerConstraint
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' attribute.
   * @see #setVariable(String)
   * @see it.csec.xtext.vsdl.VsdlPackage#getSwitch_Variable()
   * @model
   * @generated
   */
  String getVariable();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Switch#getVariable <em>Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' attribute.
   * @see #getVariable()
   * @generated
   */
  void setVariable(String value);

  /**
   * Returns the value of the '<em><b>Texp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texp</em>' containment reference.
   * @see #setTexp(TimeExpr)
   * @see it.csec.xtext.vsdl.VsdlPackage#getSwitch_Texp()
   * @model containment="true"
   * @generated
   */
  TimeExpr getTexp();

  /**
   * Sets the value of the '{@link it.csec.xtext.vsdl.Switch#getTexp <em>Texp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texp</em>' containment reference.
   * @see #getTexp()
   * @generated
   */
  void setTexp(TimeExpr value);

} // Switch
