/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Trigger Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.csec.xtext.vsdl.VsdlPackage#getUpdateTriggerConstraint()
 * @model
 * @generated
 */
public interface UpdateTriggerConstraint extends EObject
{
} // UpdateTriggerConstraint
