/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl.impl;

import it.csec.xtext.vsdl.AndOr;
import it.csec.xtext.vsdl.IPAddress;
import it.csec.xtext.vsdl.NetworkConstraint;
import it.csec.xtext.vsdl.Node;
import it.csec.xtext.vsdl.UpdateTriggerConstraint;
import it.csec.xtext.vsdl.VsdlPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And Or</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getNetworktriggerconstraint <em>Networktriggerconstraint</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getNetworkconstraint <em>Networkconstraint</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getId <em>Id</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getOp <em>Op</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getIp <em>Ip</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link it.csec.xtext.vsdl.impl.AndOrImpl#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AndOrImpl extends NodeConstraintImpl implements AndOr
{
  /**
   * The cached value of the '{@link #getNetworktriggerconstraint() <em>Networktriggerconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetworktriggerconstraint()
   * @generated
   * @ordered
   */
  protected UpdateTriggerConstraint networktriggerconstraint;

  /**
   * The cached value of the '{@link #getNetworkconstraint() <em>Networkconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetworkconstraint()
   * @generated
   * @ordered
   */
  protected NetworkConstraint networkconstraint;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected Node id;

  /**
   * The default value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected static final String OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected String op = OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getIp() <em>Ip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIp()
   * @generated
   * @ordered
   */
  protected IPAddress ip;

  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected EObject left;

  /**
   * The cached value of the '{@link #getRight() <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight()
   * @generated
   * @ordered
   */
  protected EObject right;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AndOrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VsdlPackage.Literals.AND_OR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UpdateTriggerConstraint getNetworktriggerconstraint()
  {
    return networktriggerconstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNetworktriggerconstraint(UpdateTriggerConstraint newNetworktriggerconstraint, NotificationChain msgs)
  {
    UpdateTriggerConstraint oldNetworktriggerconstraint = networktriggerconstraint;
    networktriggerconstraint = newNetworktriggerconstraint;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT, oldNetworktriggerconstraint, newNetworktriggerconstraint);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNetworktriggerconstraint(UpdateTriggerConstraint newNetworktriggerconstraint)
  {
    if (newNetworktriggerconstraint != networktriggerconstraint)
    {
      NotificationChain msgs = null;
      if (networktriggerconstraint != null)
        msgs = ((InternalEObject)networktriggerconstraint).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT, null, msgs);
      if (newNetworktriggerconstraint != null)
        msgs = ((InternalEObject)newNetworktriggerconstraint).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT, null, msgs);
      msgs = basicSetNetworktriggerconstraint(newNetworktriggerconstraint, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT, newNetworktriggerconstraint, newNetworktriggerconstraint));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NetworkConstraint getNetworkconstraint()
  {
    return networkconstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNetworkconstraint(NetworkConstraint newNetworkconstraint, NotificationChain msgs)
  {
    NetworkConstraint oldNetworkconstraint = networkconstraint;
    networkconstraint = newNetworkconstraint;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__NETWORKCONSTRAINT, oldNetworkconstraint, newNetworkconstraint);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNetworkconstraint(NetworkConstraint newNetworkconstraint)
  {
    if (newNetworkconstraint != networkconstraint)
    {
      NotificationChain msgs = null;
      if (networkconstraint != null)
        msgs = ((InternalEObject)networkconstraint).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__NETWORKCONSTRAINT, null, msgs);
      if (newNetworkconstraint != null)
        msgs = ((InternalEObject)newNetworkconstraint).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__NETWORKCONSTRAINT, null, msgs);
      msgs = basicSetNetworkconstraint(newNetworkconstraint, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__NETWORKCONSTRAINT, newNetworkconstraint, newNetworkconstraint));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Node getId()
  {
    if (id != null && id.eIsProxy())
    {
      InternalEObject oldId = (InternalEObject)id;
      id = (Node)eResolveProxy(oldId);
      if (id != oldId)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, VsdlPackage.AND_OR__ID, oldId, id));
      }
    }
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Node basicGetId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(Node newId)
  {
    Node oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOp()
  {
    return op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOp(String newOp)
  {
    String oldOp = op;
    op = newOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__OP, oldOp, op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IPAddress getIp()
  {
    return ip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIp(IPAddress newIp, NotificationChain msgs)
  {
    IPAddress oldIp = ip;
    ip = newIp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__IP, oldIp, newIp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIp(IPAddress newIp)
  {
    if (newIp != ip)
    {
      NotificationChain msgs = null;
      if (ip != null)
        msgs = ((InternalEObject)ip).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__IP, null, msgs);
      if (newIp != null)
        msgs = ((InternalEObject)newIp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__IP, null, msgs);
      msgs = basicSetIp(newIp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__IP, newIp, newIp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeft(EObject newLeft, NotificationChain msgs)
  {
    EObject oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__LEFT, oldLeft, newLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeft(EObject newLeft)
  {
    if (newLeft != left)
    {
      NotificationChain msgs = null;
      if (left != null)
        msgs = ((InternalEObject)left).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__LEFT, null, msgs);
      if (newLeft != null)
        msgs = ((InternalEObject)newLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__LEFT, null, msgs);
      msgs = basicSetLeft(newLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__LEFT, newLeft, newLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getRight()
  {
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRight(EObject newRight, NotificationChain msgs)
  {
    EObject oldRight = right;
    right = newRight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__RIGHT, oldRight, newRight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRight(EObject newRight)
  {
    if (newRight != right)
    {
      NotificationChain msgs = null;
      if (right != null)
        msgs = ((InternalEObject)right).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__RIGHT, null, msgs);
      if (newRight != null)
        msgs = ((InternalEObject)newRight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VsdlPackage.AND_OR__RIGHT, null, msgs);
      msgs = basicSetRight(newRight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VsdlPackage.AND_OR__RIGHT, newRight, newRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT:
        return basicSetNetworktriggerconstraint(null, msgs);
      case VsdlPackage.AND_OR__NETWORKCONSTRAINT:
        return basicSetNetworkconstraint(null, msgs);
      case VsdlPackage.AND_OR__IP:
        return basicSetIp(null, msgs);
      case VsdlPackage.AND_OR__LEFT:
        return basicSetLeft(null, msgs);
      case VsdlPackage.AND_OR__RIGHT:
        return basicSetRight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT:
        return getNetworktriggerconstraint();
      case VsdlPackage.AND_OR__NETWORKCONSTRAINT:
        return getNetworkconstraint();
      case VsdlPackage.AND_OR__ID:
        if (resolve) return getId();
        return basicGetId();
      case VsdlPackage.AND_OR__OP:
        return getOp();
      case VsdlPackage.AND_OR__IP:
        return getIp();
      case VsdlPackage.AND_OR__LEFT:
        return getLeft();
      case VsdlPackage.AND_OR__RIGHT:
        return getRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT:
        setNetworktriggerconstraint((UpdateTriggerConstraint)newValue);
        return;
      case VsdlPackage.AND_OR__NETWORKCONSTRAINT:
        setNetworkconstraint((NetworkConstraint)newValue);
        return;
      case VsdlPackage.AND_OR__ID:
        setId((Node)newValue);
        return;
      case VsdlPackage.AND_OR__OP:
        setOp((String)newValue);
        return;
      case VsdlPackage.AND_OR__IP:
        setIp((IPAddress)newValue);
        return;
      case VsdlPackage.AND_OR__LEFT:
        setLeft((EObject)newValue);
        return;
      case VsdlPackage.AND_OR__RIGHT:
        setRight((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT:
        setNetworktriggerconstraint((UpdateTriggerConstraint)null);
        return;
      case VsdlPackage.AND_OR__NETWORKCONSTRAINT:
        setNetworkconstraint((NetworkConstraint)null);
        return;
      case VsdlPackage.AND_OR__ID:
        setId((Node)null);
        return;
      case VsdlPackage.AND_OR__OP:
        setOp(OP_EDEFAULT);
        return;
      case VsdlPackage.AND_OR__IP:
        setIp((IPAddress)null);
        return;
      case VsdlPackage.AND_OR__LEFT:
        setLeft((EObject)null);
        return;
      case VsdlPackage.AND_OR__RIGHT:
        setRight((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT:
        return networktriggerconstraint != null;
      case VsdlPackage.AND_OR__NETWORKCONSTRAINT:
        return networkconstraint != null;
      case VsdlPackage.AND_OR__ID:
        return id != null;
      case VsdlPackage.AND_OR__OP:
        return OP_EDEFAULT == null ? op != null : !OP_EDEFAULT.equals(op);
      case VsdlPackage.AND_OR__IP:
        return ip != null;
      case VsdlPackage.AND_OR__LEFT:
        return left != null;
      case VsdlPackage.AND_OR__RIGHT:
        return right != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == NetworkConstraint.class)
    {
      switch (derivedFeatureID)
      {
        case VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT: return VsdlPackage.NETWORK_CONSTRAINT__NETWORKTRIGGERCONSTRAINT;
        case VsdlPackage.AND_OR__NETWORKCONSTRAINT: return VsdlPackage.NETWORK_CONSTRAINT__NETWORKCONSTRAINT;
        case VsdlPackage.AND_OR__ID: return VsdlPackage.NETWORK_CONSTRAINT__ID;
        case VsdlPackage.AND_OR__OP: return VsdlPackage.NETWORK_CONSTRAINT__OP;
        case VsdlPackage.AND_OR__IP: return VsdlPackage.NETWORK_CONSTRAINT__IP;
        default: return -1;
      }
    }
    if (baseClass == UpdateTriggerConstraint.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == NetworkConstraint.class)
    {
      switch (baseFeatureID)
      {
        case VsdlPackage.NETWORK_CONSTRAINT__NETWORKTRIGGERCONSTRAINT: return VsdlPackage.AND_OR__NETWORKTRIGGERCONSTRAINT;
        case VsdlPackage.NETWORK_CONSTRAINT__NETWORKCONSTRAINT: return VsdlPackage.AND_OR__NETWORKCONSTRAINT;
        case VsdlPackage.NETWORK_CONSTRAINT__ID: return VsdlPackage.AND_OR__ID;
        case VsdlPackage.NETWORK_CONSTRAINT__OP: return VsdlPackage.AND_OR__OP;
        case VsdlPackage.NETWORK_CONSTRAINT__IP: return VsdlPackage.AND_OR__IP;
        default: return -1;
      }
    }
    if (baseClass == UpdateTriggerConstraint.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (op: ");
    result.append(op);
    result.append(')');
    return result.toString();
  }

} //AndOrImpl
