/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl.impl;

import it.csec.xtext.vsdl.ConfigOptions;
import it.csec.xtext.vsdl.ConfigPair;
import it.csec.xtext.vsdl.VsdlPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Config Options</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.csec.xtext.vsdl.impl.ConfigOptionsImpl#getConfigPairs <em>Config Pairs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConfigOptionsImpl extends MinimalEObjectImpl.Container implements ConfigOptions
{
  /**
   * The cached value of the '{@link #getConfigPairs() <em>Config Pairs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfigPairs()
   * @generated
   * @ordered
   */
  protected EList<ConfigPair> configPairs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConfigOptionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VsdlPackage.Literals.CONFIG_OPTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConfigPair> getConfigPairs()
  {
    if (configPairs == null)
    {
      configPairs = new EObjectContainmentEList<ConfigPair>(ConfigPair.class, this, VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS);
    }
    return configPairs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS:
        return ((InternalEList<?>)getConfigPairs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS:
        return getConfigPairs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS:
        getConfigPairs().clear();
        getConfigPairs().addAll((Collection<? extends ConfigPair>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS:
        getConfigPairs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VsdlPackage.CONFIG_OPTIONS__CONFIG_PAIRS:
        return configPairs != null && !configPairs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ConfigOptionsImpl
