/**
 * generated by Xtext 2.35.0
 */
package it.csec.xtext.vsdl.impl;

import it.csec.xtext.vsdl.PlusMinus;
import it.csec.xtext.vsdl.VsdlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Plus Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PlusMinusImpl extends TimeExprImpl implements PlusMinus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlusMinusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VsdlPackage.Literals.PLUS_MINUS;
  }

} //PlusMinusImpl
